name: Postman Collection Workflow   # name of Github actions flow

on: # trigger
push:
branches: [main] 

workflow_dispatch:

schedule:
- cron :"30 20 * * *"
- cron :"30 20 * * *"

jobs:
Run_Postman_tests:
runs on: ubuntu-latest

steps:
-name: checkout postman Collection 
uses: uses: actions/checkout@v4.2.2 

-name: install nodejs and npm 
 uses: actions/setup-node@v3.9.1
 with:
 node-version:'18'

 -name: install newman and html extra libraries 
 run: |
 npm install -g newman
 npm install -g newman-reporter-htmlextra

 -name: Run Postman Collection 
 run: |
 newman run In_Warranty_Newman_CLI2.postman_collection \
            -e QA.postman_environment.json \
            -d testData.csv \
            -r cli,htmlextra \
            --reporter-htmlextra-export newman/index.html # index html report is stored  

 -name: Upload HTML report 
  if: always()
  uses:  actions/upload-artifact@v4.6.2
  with:
  name: Newman_report
  path: newman/*.html

  -name: send auto email 
  if: always()
  uses: dawidd6/action-send-mail@v6
  with: 
  server_address
  server_port:
  
 
 
 

 
 
